services:
  - type: web
    name: save-video-clips-bot
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg nodejs npm && npm install -g n && n lts &&
      pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
